/** @type {import('tailwindcss').Config} */
import forms from "@tailwindcss/forms";

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#505800",
        "surface-container-high": "#e7e9e2",
        "error-container": "#fd795a",
        "on-background": "#2f342e",
        "surface-variant": "#e0e4dc",
        tertiary: "#5c6400",
        "on-primary": "#ebffe0",
        secondary: "#466370",
        "on-primary-fixed": "#20481a",
        "secondary-fixed-dim": "#bbd9e9",
        "on-surface-variant": "#5c605a",
        "inverse-primary": "#cdfebe",
        "on-tertiary-container": "#525a00",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#325b2b",
        "inverse-on-surface": "#9c9d99",
        "on-error-container": "#6e1400",
        "on-secondary": "#f3faff",
        primary: "#3f6937",
        "surface-container": "#edefe8",
        "secondary-fixed": "#c9e7f7",
        "surface-dim": "#d8dbd3",
        "secondary-dim": "#3a5764",
        "primary-container": "#bff0b1",
        "surface-tint": "#3f6937",
        "on-secondary-fixed-variant": "#435f6d",
        "on-tertiary-fixed": "#414700",
        error: "#a73b21",
        outline: "#787c75",
        background: "#fafaf5",
        "on-surface": "#2f342e",
        "surface-bright": "#fafaf5",
        surface: "#fafaf5",
        "on-tertiary": "#f8ffae",
        "outline-variant": "#afb3ac",
        "on-secondary-fixed": "#264350",
        "primary-fixed-dim": "#b2e1a3",
        "error-dim": "#791903",
        "inverse-surface": "#0d0f0c",
        "on-tertiary-fixed-variant": "#5c6400",
        "on-secondary-container": "#395663",
        "primary-fixed": "#bff0b1",
        "primary-dim": "#345c2c",
        "tertiary-fixed-dim": "#d6e359",
        "secondary-container": "#c9e7f7",
        "surface-container-highest": "#e0e4dc",
        "surface-container-low": "#f3f4ee",
        "on-primary-fixed-variant": "#3c6534",
        "tertiary-container": "#e4f265",
        "on-error": "#fff7f6",
        "tertiary-fixed": "#e4f265",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        label: ["Be Vietnam Pro", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [forms],
};
